#!/usr/bin/python
import sys
from tracker import start_tracker
from peer import start_peer
from args_parser import parse_args

if __name__ == "__main__":
    # Have fun
    print("Starting P2P Application...")
    settings = parse_args(sys.argv)
    print(settings)
    if settings["role"] == "tracker":
        start_tracker(settings)
    elif settings["role"] == "peer":
        start_peer(settings)
